### ISSUE TITLE
Locator module

### ISSUE THREAD

**Issue by contervis** [contervis/KasaDaka-VSDK#1]
Investigation and implementation of a locator module to have location info at hand when needed.

**Comment by davidhuser** [comment]
Can we be more specific? A module to locate via GPS coordinates only?

**Comment by contervis** [comment]
I was thinking about a module that is being included in the views and that provides a location to the weather module. This should be done with some unified interface (Interface pattern), in this way we can both change our location or APIs sources without having to change everything around it.

**Comment by davidhuser** [comment]
Just seeing the comment now... one version is in branch `feat/gps` but probably in wrong file now... should maybe be in views.py as you say but not sure
