### ISSUE TITLE
Provide different types of storms to the caller 

### ISSUE THREAD

**Issue by shrutirao94** [contervis/KasaDaka-VSDK#18]
For Storm Alerts, I am presently considering two kinds of storms at the least: 
1. Thunderstorm
2. Dust Storm

For thunderstorm, I will require rainfall and wind information
For dust storms, I would need wind and humidity %

(See Google doc for more [information](https://docs.google.com/document/d/1kNtJGcGgjH3zmA8AZ8H2EieptazMobaSQrD_QhMNVb4/edit))

**Comment by davidhuser** [comment]
OWM would provide those elements in theory
