### ISSUE TITLE
Check timezone vs UTC

### ISSUE THREAD

**Issue by davidhuser** [contervis/KasaDaka-VSDK#29]
OWM API returns timezone info which might be different to the current system's timezone

**Comment by davidhuser** [comment]
OWM returns:
`daily.dt` = Time of the forecasted data, unix, UTC

==> so the KasaDaka should be installed as UTC (in Django & OS)

**Comment by contervis** [comment]
So the suggestion is to use the API time to adjust the Kasadaka local time before deciding the day of week for the caller?

Current daily retrieval: `weekday = datetime.datetime.today().weekday()`

**Comment by davidhuser** [comment]
I think it makes life easiest if the `vsdk/settings.py` uses a `TIME_ZONE` of `UTC`, and set the setting in Raspbian/debian to use UTC as well. This in turn would require removal of the Real-Time Clock we specified as required hardware, but if the RPi only functions _with_ Internet anyway we easily can get the time via NTP / Internet.

We should add that to the Readme issue #33
