### ISSUE TITLE
Voices Files

### ISSUE THREAD

**Issue by contervis** [contervis/KasaDaka-VSDK#3]
Creation of the voices files in two languages

**Comment by davidhuser** [comment]
is this about the software-generated voice files, or the replacement of them with real spoken language audio files?

**Comment by contervis** [comment]
So far it is about software-generated voice files, then later we can think of something nicer to substitute them

**Comment by davidhuser** [comment]
script to create voice-files https://github.com/davidhuser/csv-to-speech and its data (csv) https://docs.google.com/spreadsheets/d/1HjDThDiGQTxV6rElQMr9MoIJ7YubHkI8izUfAgukarY/edit#gid=0
