### ISSUE TITLE
Replace audio files with correct audio files and cleanup uploads folder

### ISSUE THREAD

**Issue by davidhuser** [contervis/KasaDaka-VSDK#37]
Currently there are old-style audio files with different intonation (probably fetched from FTP or older branches). Replace files (must match name). Also, cleanup the files in `uploads` that end with e.g. `_BNfTiep.wav` as they are not needed.

**Comment by davidhuser** [comment]
@contervis which folder is in actual use? there is a `vsdk/audios` and `vsdk/uploads` folder currently.

**Comment by contervis** [comment]
`vsdk/audios` contains all the audio files that we use, but `vsdk/uploads` is where a copy of them is stored after they are uploaded from the admin page. Basically the second folder contains the instance in use of the audio files in the first one.

**Comment by davidhuser** [comment]
ok thanks - so probably it's best when replacing the files in both locations @contervis ?
